timeweb/core/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url

from core import views


app_name = 'core'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(
        r'^login/',
        auth_views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='core/login.html',
        ),
        name='login',
    ),
    url(r'^logout/', auth_views.logout_then_login, name='logout'),
    url(r'^signup/', views.signup, name='signup'),
]

timeweb/tasks/urls.py
from django.conf.urls import url

from tasks import views


app_name = 'tasks'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.create, name='create'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<task_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<task_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<task_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<task_id>[0-9]+)/share/$', views.share, name='share'),
    url(r'^(?P<task_id>[0-9]+)/complete/$', views.complete, name='complete'),
    url(
        r'^(?P<task_id>[0-9]+)/uncomplete/$',
        views.uncomplete,
        name='uncomplete',
    ),
    url(r'^(?P<task_id>[0-9]+)/archive/$', views.archive, name='archive'),
    url(
        r'^(?P<task_id>[0-9]+)/unarchive/$',
        views.unarchive,
        name='unarchive',
    ),
    url(
        r'^(?P<task_id>[0-9]+)/block/(?P<blocking_task_id>[0-9]+)/$',
        views.block,
        name='block',
    ),
    url(
        r'^(?P<task_id>[0-9]+)/archive/(?P<target_task_id>[0-9]+)/$',
        views.target,
        name='target',
    ),
]

timeweb/timeweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^planned-tasks/', include('planned_tasks.urls')),
    url(r'^plans/', include('plans.urls')),
    url(r'^admin/', admin.site.urls),
]

timeweb/tasks/forms.py
from django.forms import (
    Form,
    CharField,
    ChoiceField,
    BooleanField,
    NullBooleanField,
    Textarea,
    RadioSelect,
    DateTimeField,
    DateTimeInput,
    MultipleChoiceField,
)

from timelib import TaskPriority

from core.forms import ListField


class CreateForm(Form):
    text = CharField(label='Description', widget=Textarea)
    from_time = DateTimeField(
        widget=DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        label='From',
    )
    to_time = DateTimeField(
        widget=DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        label='To',
        required=False,
    )
    priority = ChoiceField(
        label='Priority',
        widget=RadioSelect(attrs={'class': 'form-check-input'}),
        choices=[
            (priority, priority.name.capitalize())
            for priority
            in TaskPriority
        ],
        initial=TaskPriority.NORMAL,
    )
    labels = ListField(label='Labels', required=False)
    members = MultipleChoiceField(label='Members', required=False)
    blocking_tasks = MultipleChoiceField(label='Blocking tasks', required=False)
    target_tasks = MultipleChoiceField(label='Target tasks', required=False)

    def __init__(self, users, tasks, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['members'].choices = [(user.username, user.username) for user in users]
        self.fields['blocking_tasks'].choices = [(task.id, f'#{task.id} {task.text}') for task in tasks]
        self.fields['target_tasks'].choices = [(task.id, f'#{task.id} {task.text}') for task in tasks]


class EditForm(Form):
    text = CharField(
        label='Description',
        widget=Textarea,
        required=False,
    )
    from_time = DateTimeField(
        widget=DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        label='From',
        required=False,
    )
    to_time = DateTimeField(
        widget=DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        label='To',
        required=False,
    )
    priority = ChoiceField(
        label='Priority',
        widget=RadioSelect(attrs={'class': 'form-check-input'}),
        choices=[
            (priority, priority.name.capitalize())
            for priority
            in TaskPriority
        ],
        required=False,
    )
    completed = BooleanField(label='Completed', required=False)
    archived = BooleanField(label='Archived', required=False)
    labels = ListField(label='Labels', required=False)
    members = MultipleChoiceField(label='Members', required=False)
    blocking_tasks = MultipleChoiceField(label='Blocking tasks', required=False)
    target_tasks = MultipleChoiceField(label='Target tasks', required=False)

    def __init__(self, users, tasks, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['members'].choices = [(user.username, user.username) for user in users]
        self.fields['blocking_tasks'].choices = [(task.id, f'#{task.id} {task.text}') for task in tasks]
        self.fields['target_tasks'].choices = [(task.id, f'#{task.id} {task.text}') for task in tasks]


class ShareForm(Form):
    member = ChoiceField(label='Share with')

    def __init__(self, users, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['members'].choices = [(user.username, user.username) for user in users]


class SearchForm(Form):
    query = CharField(label='Query')

timeweb/tasks/views.py
from datetime import (
    datetime,
    time,
)

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse
from django.http import Http404, JsonResponse
from django.contrib.auth.models import User


from timelib.exceptions import (
    InvalidActionError,
    NotFoundError,
)

from tasks.forms import (
    CreateForm,
    EditForm,
    ShareForm,
    SearchForm,
)
from core.utils import managed


@login_required
@managed
def index(request, manager):
    users = User.objects.all()

    if request.method == 'POST':
        form = SearchForm(users, request.POST)
        if form.is_valid():
            tasks = manager.get_tasks(
                text=form.cleaned_data['text'],
                priority=form.cleaned_data['priority'] or None,
                completed=form.cleaned_data['completed'],
                archived=form.cleaned_data['archived'],
                members=form.cleaned_data['members'],
                labels=form.cleaned_data['labels'],
            )

            return render(
                request,
                'tasks/index.html',
                {'tasks': tasks, 'form': form},
            )
    else:
        form = SearchForm(users)
        tasks = manager.get_tasks(archived=False)

    return render(
        request,
        'tasks/index.html',
        {
            'tasks': tasks,
            'form': form,
        },
    )


@login_required
@managed
def detail(request, task_id, manager):
    users = User.objects.all()
    try:
        task = manager.get_task(id=int(task_id))
    except NotFoundError as e:
        raise Http404(e)

    return render(request, 'tasks/detail.html', {'task': task, 'users': users})


@login_required
@managed
def create(request, manager):
    users = User.objects.all()
    tasks = manager.get_tasks()

    if request.method == 'POST':
        form = CreateForm(users, tasks, request.POST)
        if form.is_valid():
            with manager.save_after():
                task = manager.create_task(
                    text=form.cleaned_data['text'],
                    from_time=form.cleaned_data['from_time'],
                    to_time=form.cleaned_data['to_time'],
                    priority=form.cleaned_data['priority'],
                    labels=form.cleaned_data['labels'],
                    members=form.cleaned_data['members'],
                    blocking_task_ids=list(
                        int(blocking_task)
                        for blocking_task
                        in form.cleaned_data['blocking_tasks']
                    ),
                    target_task_ids=list(
                        int(target_task)
                        for target_task
                        in form.cleaned_data['target_tasks']
                    ),
                )
            return redirect('tasks:detail', task.id)
    else:
        form = CreateForm(users, tasks)
    return render(
        request,
        'tasks/create.html',
        {
            'form': form,
        },
    )


@login_required
@managed
def edit(request, task_id, manager):
    users = User.objects.all()
    tasks = manager.get_tasks()
    task = manager.get_task(id=int(task_id))

    if request.method == 'POST':
        form = EditForm(users, tasks, request.POST)
        if form.is_valid():
            with manager.save_after():
                task.text = form.cleaned_data['text']
                task.from_time = form.cleaned_data.get(
                    'from_time',
                    task.from_time,
                )
                task.to_time = form.cleaned_data.get(
                    'to_time',
                    task.to_time,
                )
                task.priority = form.cleaned_data['priority']
                task.completed = form.cleaned_data['completed']
                task.archived = form.cleaned_data['archived']
                task.blocking_tasks = [
                    manager.get_task(id=int(blocking_task_id))
                    for blocking_task_id
                    in form.cleaned_data['blocking_tasks']
                ]
                task.target_tasks = [
                    manager.get_task(id=int(target_task_id))
                    for target_task_id
                    in form.cleaned_data['target_tasks']
                ]
                task.labels = form.cleaned_data['labels']
                task.members = list(
                    set(
                        form.cleaned_data['members']
                        + [request.user.username],
                    ),
                )
            return redirect(
                request.POST.get(
                    'next',
                    reverse('tasks:detail', args=[task_id]),
                ),
            )
    else:
        form = EditForm(
            users,
            tasks,
            initial={
                **vars(task),
                'priority': task.priority,
                'blocking_tasks': [
                    str(blocking_task.id)
                    for blocking_task
                    in task.blocking_tasks
                ],
                'target_tasks': [
                    str(target_task.id)
                    for target_task
                    in task.target_tasks
                ],
            },
        )

    return render(
        request,
        'tasks/edit.html',
        {
            'form': form,
            'task': task,
            'next': request.GET.get(
                'next',
                reverse('tasks:detail', args=[task_id]),
            ),
        },
    )


@login_required
@managed
def delete(request, task_id, manager):
    with manager.save_after():
        manager.delete_task(id=int(task_id))

    return redirect(
        request.GET.get('next', request.POST.get('next', 'tasks:index')),
    )


@login_required
@managed
def share(request, task_id, manager):
    task = manager.get_task(id=int(task_id))
    users = User.objects.all()

    if request.method == 'POST':
        form = ShareForm(users, request.POST)
        if form.data.get('member'):
            with manager.save_after():
                manager.share_task(
                    id=task.id,
                    members=[form.data['member']],
                )
            return redirect(
                request.POST.get(
                    'next',
                    reverse('tasks:detail', args=[task_id]),
                ),
            )

    return render(
        request,
        'tasks/share.html',
        {
            'task': task,
            'next': request.GET.get(
                'next',
                reverse('tasks:detail', args=[task_id]),
            ),
            'users': users,
        },
    )


@login_required
@managed
def complete(request, task_id, manager):
    try:
        with manager.save_after():
            task = manager.get_task(id=int(task_id))
            manager.complete_task(id=task.id)
    except InvalidActionError as e:
        return redirect(
            request.GET.get(
                "next",
                request.POST.get(
                    "next",
                    reverse("tasks:detail", args=[task_id]),
                ),
            )
            + f'?error={e}',
        )

    return redirect(
        request.GET.get(
            'next',
            request.POST.get('next', reverse('tasks:detail', args=[task_id])),
        ),
    )


@login_required
@managed
def uncomplete(request, task_id, manager):
    with manager.save_after():
        task = manager.get_task(id=int(task_id))
        task.completed = False

    return redirect(
        request.GET.get(
            'next',
            request.POST.get('next', reverse('tasks:detail', args=[task_id])),
        ),
    )


@login_required
@managed
def archive(request, task_id, manager):
    with manager.save_after():
        task = manager.get_task(id=int(task_id))
        task.archived = True

    return redirect(
        request.GET.get(
            'next',
            request.POST.get('next', reverse('tasks:detail', args=[task_id])),
        ),
    )


@login_required
@managed
def unarchive(request, task_id, manager):
    with manager.save_after():
        task = manager.get_task(id=int(task_id))
        task.archived = False

    return redirect(
        request.GET.get(
            'next',
            request.POST.get('next', reverse('tasks:detail', args=[task_id])),
        ),
    )


@login_required
@managed
def block(request, task_id, blocking_task_id, manager):
    with manager.save_after():
        task = manager.get_task(id=int(task_id))
        blocking = manager.get_task(id=int(blocking_task_id))
        task.blocking_tasks = list(set(task.blocking_tasks + [blocking]))

    return redirect(
        request.GET.get(
            'next',
            request.POST.get('next', reverse('tasks:detail', args=[task_id])),
        ),
    )


@login_required
@managed
def target(request, task_id, target_task_id, manager):
    with manager.save_after():
        task = manager.get_task(id=int(task_id))
        target = manager.get_task(id=int(target_task_id))
        task.target_tasks = list(set(task.target_tasks + [target]))

    return redirect(
        request.GET.get(
            'next',
            request.POST.get('next', reverse('tasks:detail', args=[task_id])),
        ),
    )


@login_required
@managed
def search(request, manager):
    def predicate(term, task):
        if term in task.text:
            return True
        elif term.startswith('@'):
            return term[1:] in task.members
        elif term.startswith('#'):
            return any(term[1:] == label or label.startswith(f'{term[1:]}.') for label in task.labels)
        elif all(letter == '!' for letter in term):
            return 5 - len(term) == task.priority
        elif term.lower() == 'completed':
            return task.completed
        elif term.lower() in ['uncompleted', 'incompleted']:
            return not task.completed

timeweb/tasks/templates/tasks/base.html
{% extends 'base.html' %}

{% block tabs %}{% include 'tabs_snippet.html' with active_tab='tasks' %}{% endblock %}

timeweb/tasks/templates/tasks/compact_snippet.html
<a class="badge badge-pill
    {% if task.priority == 'TaskPriority.CRITICAL' %}
        badge-danger
    {% elif task.priority == 'TaskPriority.IMPORTANT' %}
        badge-warning
    {% elif task.priority == 'TaskPriority.NORMAL' %}
        badge-primary
    {% elif task.priority == 'TaskPriority.LOW' %}
        badge-secondary
    {% endif %}
" href="{% url 'tasks:detail' task.id %}">
    #{{ task.id }}
    {% if task.completed %}<small class="oi oi-check"></small>{% endif %}
    {% if task.archived %}<small class="oi oi-box"></small>{% endif %}
    {{ task.text|truncatechars:20 }}
    {% if task.labels %}<small class="oi oi-tags"></small> {{ task.labels|length }}{% endif %}
    {% if task.members %}<small class="oi oi-people"></small> {{ task.members|length }}{% endif %}
    {% if task.blocking_tasks %}<small class="oi oi-lock-locked"></small> {{ task.blocking_tasks|length }}{% endif %}
    {% if task.target_tasks %}<small class="oi oi-flash"></small> {{ task.target_tasks|length }}{% endif %}
</a>

timeweb/tasks/templates/tasks/detail.html
{% extends 'tasks/base.html' %}

{% load core_extras %}

{% block content %}
    <div class="container py-3">
        {% if 'error' in request.GET %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ request.GET.error }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">
                    #{{ task.id }}
                    {% if task.priority == 'TaskPriority.CRITICAL' %}
                        <span class="badge badge-danger">CRITICAL</span>
                    {% elif task.priority == 'TaskPriority.IMPORTANT' %}
                        <span class="badge badge-warning">IMPORTANT</span>
                    {% elif task.priority == 'TaskPriority.NORMAL' %}
                        <span class="badge badge-primary">NORMAL</span>
                    {% elif task.priority == 'TaskPriority.LOW' %}
                        <span class="badge badge-secondary">LOW</span>
                    {% endif %}
                    {% if task.completed %}<span class="badge badge-pill badge-success"><small class="oi oi-check"></small> completed</span>{% endif %}
                    {% if task.archived %}<span class="badge badge-pill badge-info"><small class="oi oi-box"></small> archived</span>{% endif %}
                </h4>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Time:</div>
                        <div class="col">
                            {{ task.from_time }}{% if task.to_time %} - {{ task.to_time }}{% endif %}
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Labels:</div>
                        <div class="col">
                            <ul class="list-inline">
                                {% for label in task.labels %}
                                    <li class="list-inline-item"><span class="badge badge-pill badge-primary">{{ label }}</span></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Members:</div>
                        <div class="col">
                            <ul class="list-inline">
                                {% for member in task.members %}
                                    <li class="list-inline-item"><span class="badge badge-pill badge-primary"><small class="oi oi-person"></small> {{ member }}</span></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Created:</div>
                        <div class="col">
                            {{ task.created_at }}
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Updated:</div>
                        <div class="col">
                            {{ task.updated_at }}
                        </div>
                    </div>
                </li>
                {% if task.blocking_tasks %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col col-2">Blocking tasks:</div>
                            <div class="col">
                                <ul class="list-inline">
                                    {% for blocking_task in task.blocking_tasks %}
                                        <li class="list-inline-item">{% include 'tasks/compact_snippet.html' with task=blocking_task %}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </li>
                {% endif %}
                {% if task.target_tasks %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col col-2">Target tasks:</div>
                            <div class="col">
                                <ul class="list-inline">
                                    {% for target_task in task.target_tasks %}
                                        <li class="list-inline-item">{% include 'tasks/compact_snippet.html' with task=target_task %}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </li>
                {% endif %}
            </ul>
            <div class="card-body">
                {{ task.text }}
            </div>
            <div class="card-body">
                {% if task.completed %}
                    <a class="btn btn-primary" href="{% url 'tasks:uncomplete' task.id %}?next={{ request.path }}">Uncomplete</a>
                {% else %}
                    <a class="btn btn-success{% if not task.blocking_tasks|all_completed %} disabled{% endif %}" href="{% url 'tasks:complete' task.id %}?next={{ request.path }}">Complete</a>
                {% endif %}
                {% if task.archived %}
                    <a class="btn btn-primary" href="{% url 'tasks:unarchive' task.id %}?next={{ request.path }}">Unarchive</a>
                {% else %}
                    <a class="btn btn-primary" href="{% url 'tasks:archive' task.id %}?next={{ request.path }}">Archive</a>
                {% endif %}
                <div class="dropdown d-inline-block">
                    <button class="btn btn-primary dropdown-toggle" type="button" id="share-task-{{ task.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Share</button>
                    <div class="dropdown-menu p-4" aria-labelledby="share-task-{{ task.id }}">
                        {% include 'tasks/share_snippet.html' with task=task next=request.path users=users %}
                    </div>
                </div>
                <a class="btn btn-danger" href="{% url 'tasks:delete' task.id %}">Delete</a>
                <a href="{% url 'tasks:edit' task.id %}?next={{ request.path }}" class="btn btn-link">Edit</a>
            </div>
        </div>
    </div>
{% endblock %}

timeweb/tasks/templates/tasks/index.html
{% extends 'tasks/base.html' %}

{% load widget_tweaks %}
{% load staticfiles %}

{% block content %}
    <script src="{% static 'tasks/search.js' %}"></script>
    <div class="container py-3">
        {% if 'error' in request.GET %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ request.GET.error }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="dropdown">
            <input type="text" class="form-control mb-2" id="search" placeholder="Task search query" data-toggle="dropdown" autocomplete="off">
            <div class="dropdown-menu" style="width: 100%;"></div>
        </div>
        <script>
            document.addEventListener('DOMContentLoaded', () => {
                const search = document.querySelector('#search');
                const menu = search.nextElementSibling;
                const searchController = new SearchController();
                search.addEventListener(
                    'input',
                    e => {
                        searchController.search(e.target.value)
                            .then(
                                tasks => {
                                    menu.innerHTML = '';
                                    for (const task of tasks) {
                                        const item = document.createElement('a');
                                        item.className = 'dropdown-item';
                                        item.setAttribute('href', `/tasks/${task.id}/`);
                                        item.innerHTML = `#${task.id} ${task.text}`;
                                        menu.appendChild(item);
                                    }
                                }
                            );
                    }
                );
            });
        </script>
        <h3>Tasks</h3>
        {% include 'tasks/list_snippet.html' with tasks=tasks %}
        <a class="btn btn-primary" href="{% url 'tasks:create' %}">Add task</a>
    </div>
{% endblock %}

timeweb/tasks/templates/tasks/list_snippet.html
{% load core_extras %}

<table class="table">
    {% if tasks %}
        <tbody>
            {% for task in tasks %}
                <tr>
                    <th scope="row">
                        <a href="{% url 'tasks:detail' task.id %}">#{{ task.id }}</a>
                        {% if task.priority == 'TaskPriority.CRITICAL' %}
                            <span class="badge badge-danger">CRITICAL</span>
                        {% elif task.priority == 'TaskPriority.IMPORTANT' %}
                            <span class="badge badge-warning">IMPORTANT</span>
                        {% elif task.priority == 'TaskPriority.NORMAL' %}
                            <span class="badge badge-primary">NORMAL</span>
                        {% elif task.priority == 'TaskPriority.LOW' %}
                            <span class="badge badge-secondary">LOW</span>
                        {% endif %}
                        {% if task.blocking_tasks %}<span class="badge badge-pill badge-primary"><small class="oi oi-lock-locked"></small> {{ task.blocking_tasks|length }}</span>{% endif %}
                        {% if task.target_tasks %}<span class="badge badge-pill badge-primary"><small class="oi oi-flash"></small> {{ task.target_tasks|length }}</span>{% endif %}
                        {% if task.completed %}<span class="badge badge-pill badge-success"><small class="oi oi-check"></small> completed</span>{% endif %}
                        {% if task.archived %}<span class="badge badge-pill badge-info"><small class="oi oi-box"></small> archived</span>{% endif %}
                    </th>
                    <td><a href="{% url 'tasks:detail' task.id %}">{{ task.text|truncatechars:50 }}</a></td>
                    <td>
                        {{ task.from_time }}{% if task.to_time %} - {{ task.to_time }}{% endif %}
                    </td>
                    <td>
                        <ul class="list-inline">
                            {% for label in task.labels %}
                                <li class="list-inline-item"><span class="badge badge-pill badge-primary">{{ label }}</span></li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <ul class="list-inline">
                            {% for member in task.members %}
                                <li class="list-inline-item"><span class="badge badge-pill badge-primary"><small class="oi oi-person"></small> {{ member }}</span></li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        {% if task.completed %}
                            <a class="btn btn-primary" href="{% url 'tasks:uncomplete' task.id %}?next={{ request.path }}">Uncomplete</a>
                        {% else %}
                            <a class="btn btn-success{% if not task.blocking_tasks|all_completed %} disabled{% endif %}" href="{% url 'tasks:complete' task.id %}?next={{ request.path }}">Complete{% if task.target_tasks %} <span class="badge badge-light"><small class="oi oi-flash"></small> {{ task.target_tasks|length }}</span>{% endif %}</a>
                        {% endif %}
                    </td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-link" type="button" id="task-menu-{{ task.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="oi oi-menu"></span></button>
                            <div class="dropdown-menu" aria-labelledby="task-menu-{{ task.id }}">
                                <a class="dropdown-item" href="{% url 'tasks:edit' task.id %}?next={{ request.path }}"><span class="oi oi-pencil"></span> Edit</a>
                                {% if task.archived %}
                                    <a class="dropdown-item" href="{% url 'tasks:unarchive' task.id %}?next={{ request.path }}"><span class="oi oi-box"></span> Unarchive</a>
                                {% else %}
                                    <a class="dropdown-item" href="{% url 'tasks:archive' task.id %}?next={{ request.path }}"><span class="oi oi-box"></span> Archive</a>
                                {% endif %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'tasks:delete' task.id %}?next={{ request.path }}"><span class="oi oi-trash"></span> Delete</a>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    {% else %}
        <div class="alert alert-primary">No tasks in this list</div>
    {% endif %}
</table>

timeweb/tasks/templates/tasks/share.html
{% extends 'tasks/base.html' %}

{% block content %}
    <div class="container py-3">
        {% include 'tasks/share_snippet.html' with task=task next=next users=users %}
    </div>
{% endblock %}

timeweb/tasks/templates/tasks/share_snippet.html
<form action="{% url 'tasks:share' task.id %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="member-input-{{ task.id }}">Share with:</label>
        <select class="form-control" name="member" id="member-input-{{ task.id }}">
            {% for user in users %}
                <option value="{{ user.username }}">{{ user.username }}</option>
            {% endfor %}
        </select>
    </div>
    <input type="hidden" value="{{ next }}">
    <input class="btn btn-primary" type="submit" value="Share">
</form>