timeweb/core/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url

from core import views


app_name = 'core'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(
        r'^login/',
        auth_views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='core/login.html',
        ),
        name='login',
    ),
    url(r'^logout/', auth_views.logout_then_login, name='logout'),
    url(r'^signup/', views.signup, name='signup'),
]

timeweb/planned_tasks/urls.py
from django.conf.urls import url

from planned_tasks import views


app_name = 'planned_tasks'
urlpatterns = [
    url(r'^add/$', views.create, name='create'),
    url(r'^(?P<planned_task_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<planned_task_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<planned_task_id>[0-9]+)/delete/$', views.delete, name='delete'),
]

timeweb/timeweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^planned-tasks/', include('planned_tasks.urls')),
    url(r'^plans/', include('plans.urls')),
    url(r'^admin/', admin.site.urls),
]

timeweb/planned_tasks/forms.py
from django.forms import (
    Form,
    ChoiceField,
    CharField,
    BooleanField,
    Textarea,
    RadioSelect,
    IntegerField,
    MultipleChoiceField,
)
from timelib import TaskPriority

from core.forms import ListField, RelativedeltaField


class CreateForm(Form):
    plan_id = IntegerField(label='Plan')
    text = CharField(label='Description', widget=Textarea)
    from_time = RelativedeltaField(label='From')
    to_time = RelativedeltaField(label='To', required=False)
    priority = ChoiceField(
        label='Priority',
        widget=RadioSelect(attrs={'class': 'form-check-input'}),
        choices=[
            (priority, priority.name.capitalize())
            for priority
            in TaskPriority
        ],
        initial=TaskPriority.NORMAL,
    )
    labels = ListField(label='Labels', required=False)
    members = MultipleChoiceField(label='Members', required=False)
    blocking_tasks = MultipleChoiceField(label='Blocking tasks', required=False)
    target_tasks = MultipleChoiceField(label='Target tasks', required=False)

    def __init__(self, users, planned_tasks, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['members'].choices = [(user.username, user.username) for user in users]
        self.fields['blocking_tasks'].choices = [(task.id, f'#{task.id} {task.text}') for task in planned_tasks]
        self.fields['target_tasks'].choices = [(task.id, f'#{task.id} {task.text}') for task in planned_tasks]


class EditForm(Form):
    plan_id = IntegerField(label='Plan')
    text = CharField(label='Description', widget=Textarea)
    from_time = RelativedeltaField(label='From')
    to_time = RelativedeltaField(label='To', required=False)
    priority = ChoiceField(
        label='Priority',
        widget=RadioSelect(attrs={'class': 'form-check-input'}),
        choices=[
            (priority, priority.name.capitalize())
            for priority
            in TaskPriority
        ],
        required=False,
    )
    completed = BooleanField(label='Completed', required=False)
    archived = BooleanField(label='Archived', required=False)
    labels = ListField(label='Labels', required=False)
    members = MultipleChoiceField(label='Members', required=False)
    blocking_tasks = MultipleChoiceField(label='Blocking tasks', required=False)
    target_tasks = MultipleChoiceField(label='Target tasks', required=False)

    def __init__(self, users, planned_tasks, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['members'].choices = [(user.username, user.username) for user in users]
        self.fields['blocking_tasks'].choices = [(task.id, f'#{task.id} {task.text}') for task in planned_tasks]
        self.fields['target_tasks'].choices = [(task.id, f'#{task.id} {task.text}') for task in planned_tasks]

timeweb/planned_tasks/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User

from planned_tasks.forms import (
    CreateForm,
    EditForm,
)
from core.utils import managed


@login_required
@managed
def detail(request, planned_task_id, manager):
    planned_task = manager.get_planned_task(id=int(planned_task_id))

    return render(
        request,
        'planned_tasks/detail.html',
        {'planned_task': planned_task},
    )


@login_required
@managed
def create(request, manager):
    users = User.objects.all()

    if request.method == 'POST':
        planned_tasks = manager.get_planned_tasks(plan_id=int(request.POST['plan_id']))
        form = CreateForm(users, planned_tasks, request.POST)
        if form.is_valid():
            with manager.save_after():
                planned_task = manager.create_planned_task(
                    plan_id=form.cleaned_data['plan_id'],
                    text=form.cleaned_data['text'],
                    from_time=form.cleaned_data['from_time'],
                    to_time=form.cleaned_data['to_time'],
                    priority=form.cleaned_data['priority'],
                    labels=form.cleaned_data['labels'],
                    members=form.cleaned_data['members'],
                    blocking_task_ids=list(
                        int(blocking_task)
                        for blocking_task
                        in form.cleaned_data['blocking_tasks']
                    ),
                    target_task_ids=list(
                        int(target_task)
                        for target_task
                        in form.cleaned_data['target_tasks']
                    ),
                )
            return redirect('planned_tasks:detail', planned_task.id)
    else:
        planned_tasks = manager.get_planned_tasks(plan_id=int(request.GET['plan_id']))
        form = CreateForm(users, planned_tasks, initial={'plan_id': request.GET.get('plan_id')})

    return render(request, 'planned_tasks/create.html', {'form': form})


@login_required
@managed
def edit(request, planned_task_id, manager):
    planned_task = manager.get_planned_task(id=int(planned_task_id))
    users = User.objects.all()
    planned_tasks = manager.get_planned_tasks(plan_id=planned_task.plan_id)

    if request.method == 'POST':
        form = EditForm(users, planned_tasks, request.POST)
        if form.is_valid():
            with manager.save_after():
                planned_task.plan_id = form.cleaned_data['plan_id']
                planned_task.text = form.cleaned_data['text']
                planned_task.from_time = form.cleaned_data['from_time']
                planned_task.to_time = form.cleaned_data['to_time']
                planned_task.priority = form.cleaned_data['priority']
                planned_task.completed = form.cleaned_data['completed']
                planned_task.archived = form.cleaned_data['archived']
                planned_task.blocking_tasks = [
                    manager.get_planned_task(id=int(blocking_task_id))
                    for blocking_task_id
                    in form.cleaned_data['blocking_tasks']
                ]
                planned_task.target_tasks = [
                    manager.get_planned_task(id=int(target_task_id))
                    for target_task_id
                    in form.cleaned_data['target_tasks']
                ]
                planned_task.labels = form.cleaned_data['labels']
                planned_task.members = list(
                    set(
                        form.cleaned_data['members']
                        + [request.user.username],
                    ),
                )
            return redirect(
                request.POST.get(
                    'next',
                    reverse('planned_tasks:detail', args=[planned_task_id]),
                ),
            )
    else:
        form = EditForm(
            users,
            planned_tasks,
            initial={
                **vars(planned_task),
                'priority': planned_task.priority,
                'blocking_tasks': [
                    str(blocking_task.id)
                    for blocking_task
                    in planned_task.blocking_tasks
                ],
                'target_tasks': [
                    str(target_task.id)
                    for target_task
                    in planned_task.target_tasks
                ],
            },
        )

    return render(
        request,
        'planned_tasks/edit.html',
        {
            'form': form,
            'planned_task': planned_task,
            'next': request.GET.get(
                'next',
                reverse('planned_tasks:detail', args=[planned_task_id]),
            ),
        },
    )


@login_required
@managed
def delete(request, planned_task_id, manager):
    with manager.save_after():
        planned_task = manager.get_planned_task(id=int(planned_task_id))
        plan = planned_task.plan
        manager.delete_planned_task(id=planned_task.id)

    return redirect(
        request.GET.get(
            'next',
            request.POST.get('next', reverse('plans:detail', args=[plan.id])),
        ),
    )

timeweb/planned_tasks/templates/planned_tasks/base.html
{% extends 'base.html' %}

{% block tabs %}{% include 'tabs_snippet.html' with active_tab='plans' %}{% endblock %}

timeweb/planned_tasks/templates/planned_tasks/compact_snippet.html
<a class="badge badge-pill
    {% if planned_task.priority == 'TaskPriority.CRITICAL' %}
        badge-danger
    {% elif planned_task.priority == 'TaskPriority.IMPORTANT' %}
        badge-warning
    {% elif planned_task.priority == 'TaskPriority.NORMAL' %}
        badge-primary
    {% elif planned_task.priority == 'TaskPriority.LOW' %}
        badge-secondary
    {% endif %}
" href="{% url 'planned_tasks:detail' planned_task.id %}">
    #{{ planned_task.id }}
    {% if planned_task.completed %}<small class="oi oi-check"></small>{% endif %}
    {% if planned_task.archived %}<small class="oi oi-box"></small>{% endif %}
    {{ planned_task.text|truncatechars:20 }}
    <small class="oi oi-timer"></small> #{{ planned_task.plan_id }}
    {% if planned_task.labels %}<small class="oi oi-tags"></small> {{ planned_task.labels|length }}{% endif %}
    {% if planned_task.members %}<small class="oi oi-people"></small> {{ planned_task.members|length }}{% endif %}
    {% if planned_task.blocking_tasks %}<small class="oi oi-lock-locked"></small> {{ planned_task.blocking_tasks|length }}{% endif %}
    {% if planned_task.target_tasks %}<small class="oi oi-flash"></small> {{ planned_task.target_tasks|length }}{% endif %}
</a>

timeweb/planned_tasks/templates/planned_tasks/create.html
{% extends 'planned_tasks/base.html' %}

{% load widget_tweaks %}

{% block content %}
    <div class="container py-3">
        <form action="{% url 'planned_tasks:create' %}" method="POST">
            {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            {% csrf_token %}
            <div class="form-group">
                {{ form.text.label_tag }}
                {% if form.text.errors %}
                    {{ form.text|add_class:'form-control is-invalid'|attr:'rows:3' }}
                    <div class="invalid-feedback">{{ form.text.errors }}</div>
                {% else %}
                    {{ form.text|add_class:'form-control'|attr:'rows:3' }}
                {% endif %}
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ form.from_time.label_tag }}
                        {% if form.from_time.errors %}
                            {{ form.from_time|add_class:'form-control is-invalid'|attr:'placeholder:1 weeks 11 hours 3 days' }}
                            <div class="invalid-feedback">{{ form.from_time.errors }}</div>
                        {% else %}
                            {{ form.from_time|add_class:'form-control'|attr:'placeholder:1 weeks 11 hours 3 days' }}
                        {% endif %}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {{ form.to_time.label_tag }}
                        {% if form.to_time.errors %}
                            {{ form.to_time|add_class:'form-control is-invalid'|attr:'placeholder:1 weeks 11 hours 3 days' }}
                            <div class="invalid-feedback">{{ form.to_time.errors }}</div>
                        {% else %}
                            {{ form.to_time|add_class:'form-control'|attr:'placeholder:1 weeks 11 hours 3 days' }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.labels.label_tag }}
                {% if form.labels.errors %}
                    {{ form.labels|add_class:'form-control is-invalid'|attr:'placeholder:label.sublabel labs.tas edu.tas' }}
                    <div class="invalid-feedback">{{ form.labels.errors }}</div>
                {% else %}
                    {{ form.labels|add_class:'form-control'|attr:'placeholder:label.sublabel labs.tas edu.tas' }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.members.label_tag }}
                {% if form.members.errors %}
                    {{ form.members|add_class:'form-control is-invalid' }}
                    <div class="invalid-feedback">{{ form.members.errors }}</div>
                {% else %}
                    {{ form.members|add_class:'form-control' }}
                {% endif %}
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ form.blocking_tasks.label_tag }}
                        {% if form.blocking_tasks.errors %}
                            {{ form.blocking_tasks|add_class:'form-control is-invalid' }}
                            <div class="invalid-feedback">{{ form.blocking_tasks.errors }}</div>
                        {% else %}
                            {{ form.blocking_tasks|add_class:'form-control' }}
                        {% endif %}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {{ form.target_tasks.label_tag }}
                        {% if form.target_tasks.errors %}
                            {{ form.target_tasks|add_class:'form-control is-invalid' }}
                            <div class="invalid-feedback">{{ form.target_tasks.errors }}</div>
                        {% else %}
                            {{ form.target_tasks|add_class:'form-control' }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.priority.label_tag }}
                {% for prior in form.priority %}
                    <div class="form-check">
                        {{ prior.tag }}
                        <label for="{{ prior.id_for_label }}">{{ prior.choice_label }}</label>
                    </div>
                {% endfor %}
                {% if form.priority.errors %}
                    <div class="invalid-feedback">{{ form.priority.errors }}</div>
                {% endif %}
            </div>
            {% render_field form.plan_id type='hidden' %}
            <input class="btn btn-primary" type="submit" value="Create">
        </form>
    </div>
{% endblock %}

timeweb/planned_tasks/templates/planned_tasks/detail.html
{% extends 'planned_tasks/base.html' %}

{% load core_extras %}

{% block content %}
    <div class="container py-3">
        {% if 'error' in request.GET %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ request.GET.error }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">
                    #{{ planned_task.id }}
                    {% if planned_task.priority == 'TaskPriority.CRITICAL' %}
                        <span class="badge badge-danger">CRITICAL</span>
                    {% elif planned_task.priority == 'TaskPriority.IMPORTANT' %}
                        <span class="badge badge-warning">IMPORTANT</span>
                    {% elif planned_task.priority == 'TaskPriority.NORMAL' %}
                        <span class="badge badge-primary">NORMAL</span>
                    {% elif planned_task.priority == 'TaskPriority.LOW' %}
                        <span class="badge badge-secondary">LOW</span>
                    {% endif %}
                    {% if planned_task.completed %}<span class="badge badge-pill badge-success"><small class="oi oi-check"></small> completed</span>{% endif %}
                    {% if planned_task.archived %}<span class="badge badge-pill badge-info"><small class="oi oi-box"></small> archived</span>{% endif %}
                </h4>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Plan:</div>
                        <div class="col">
                            {% include 'plans/compact_snippet.html' with plan=planned_task.plan %}
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Time:</div>
                        <div class="col">
                            {{ planned_task.from_time|relativedelta }}{% if planned_task.to_time %} - {{ planned_task.to_time|relativedelta }}{% endif %}
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Labels:</div>
                        <div class="col">
                            <ul class="list-inline">
                                {% for label in planned_task.labels %}
                                    <li class="list-inline-item"><span class="badge badge-pill badge-primary">{{ label }}</span></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Members:</div>
                        <div class="col">
                            <ul class="list-inline">
                                {% for member in planned_task.members %}
                                    <li class="list-inline-item"><span class="badge badge-pill badge-primary"><small class="oi oi-person"></small> {{ member }}</span></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </li>
                {% if planned_task.blocking_tasks %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col col-2">Blocking tasks:</div>
                            <div class="col">
                                <ul class="list-inline">
                                    {% for blocking_task in planned_task.blocking_tasks %}
                                        <li class="list-inline-item">{% include 'planned_tasks/compact_snippet.html' with planned_task=blocking_task %}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </li>
                {% endif %}
                {% if planned_task.target_tasks %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col col-2">Target tasks:</div>
                            <div class="col">
                                <ul class="list-inline">
                                    {% for target_task in planned_task.target_tasks %}
                                        <li class="list-inline-item">{% include 'planned_tasks/compact_snippet.html' with planned_task=target_task %}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </li>
                {% endif %}
            </ul>
            <div class="card-body">
                {{ planned_task.text }}
            </div>
            <div class="card-body">
                <a class="btn btn-danger" href="{% url 'planned_tasks:delete' planned_task.id %}">Delete</a>
                <a href="{% url 'planned_tasks:edit' planned_task.id %}?next={{ request.path }}" class="btn btn-link">Edit</a>
            </div>
        </div>
    </div>
{% endblock %}

timeweb/planned_tasks/templates/planned_tasks/edit.html
{% extends 'planned_tasks/base.html' %}

{% load widget_tweaks %}

{% block content %}
    <div class="container py-3">
        <form action="{% url 'planned_tasks:edit' planned_task.id %}" method="POST">
            {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            {% csrf_token %}
            <div class="form-group">
                {{ form.text.label_tag }}
                {% if form.text.errors %}
                    {{ form.text|add_class:'form-control is-invalid'|attr:'rows:3' }}
                    <div class="invalid-feedback">{{ form.text.errors }}</div>
                {% else %}
                    {{ form.text|add_class:'form-control'|attr:'rows:3' }}
                {% endif %}
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ form.from_time.label_tag }}
                        {% if form.from_time.errors %}
                            {{ form.from_time|add_class:'form-control is-invalid' }}
                            <div class="invalid-feedback">{{ form.from_time.errors }}</div>
                        {% else %}
                            {{ form.from_time|add_class:'form-control' }}
                        {% endif %}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {{ form.to_time.label_tag }}
                        {% if form.to_time.errors %}
                            {{ form.to_time|add_class:'form-control is-invalid' }}
                            <div class="invalid-feedback">{{ form.to_time.errors }}</div>
                        {% else %}
                            {{ form.to_time|add_class:'form-control' }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.labels.label_tag }}
                {% if form.labels.errors %}
                    {{ form.labels|add_class:'form-control is-invalid' }}
                    <div class="invalid-feedback">{{ form.labels.errors }}</div>
                {% else %}
                    {{ form.labels|add_class:'form-control' }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.members.label_tag }}
                {% if form.members.errors %}
                    {{ form.members|add_class:'form-control is-invalid' }}
                    <div class="invalid-feedback">{{ form.members.errors }}</div>
                {% else %}
                    {{ form.members|add_class:'form-control' }}
                {% endif %}
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ form.blocking_tasks.label_tag }}
                        {% if form.blocking_tasks.errors %}
                            {{ form.blocking_tasks|add_class:'form-control is-invalid' }}
                            <div class="invalid-feedback">{{ form.blocking_tasks.errors }}</div>
                        {% else %}
                            {{ form.blocking_tasks|add_class:'form-control' }}
                        {% endif %}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {{ form.target_tasks.label_tag }}
                        {% if form.target_tasks.errors %}
                            {{ form.target_tasks|add_class:'form-control is-invalid' }}
                            <div class="invalid-feedback">{{ form.target_tasks.errors }}</div>
                        {% else %}
                            {{ form.target_tasks|add_class:'form-control' }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-check">
                {% if form.completed.errors %}
                    {{ form.completed|add_class:'form-check-input is-invalid' }}
                    <label class="form-check-label" for="{{ form.completed.id_for_label }}">{{ form.completed.label }}</label>
                    <div class="invalid-feedback">{{ form.completed.errors }}</div>
                {% else %}
                    {{ form.completed|add_class:'form-check-input' }}
                    <label class="form-check-label" for="{{ form.completed.id_for_label }}">{{ form.completed.label }}</label>
                {% endif %}
            </div>
            <div class="form-check">
                {% if form.archived.errors %}
                    {{ form.archived|add_class:'form-check-input is-invalid' }}
                    <label class="form-check-label" for="{{ form.archived.id_for_label }}">{{ form.archived.label }}</label>
                    <div class="invalid-feedback">{{ form.archived.errors }}</div>
                {% else %}
                    {{ form.archived|add_class:'form-check-input' }}
                    <label class="form-check-label" for="{{ form.archived.id_for_label }}">{{ form.archived.label }}</label>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.priority.label_tag }}
                {% for prior in form.priority %}
                    <div class="form-check">
                        {{ prior.tag }}
                        <label for="{{ prior.id_for_label }}">{{ prior.choice_label }}</label>
                    </div>
                {% endfor %}
                {% if form.priority.errors %}
                    <div class="invalid-feedback">{{ form.priority.errors }}</div>
                {% endif %}
            </div>
            {% render_field form.plan_id type='hidden' %}
            <input type="hidden" name="next" value="{{ next }}">
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
{% endblock %}