timeweb/core/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url

from core import views


app_name = 'core'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(
        r'^login/',
        auth_views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='core/login.html',
        ),
        name='login',
    ),
    url(r'^logout/', auth_views.logout_then_login, name='logout'),
    url(r'^signup/', views.signup, name='signup'),
]

timeweb/plans/urls.py
from django.conf.urls import url

from plans import views


app_name = 'plans'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.create, name='create'),
    url(r'^check/$', views.check, name='check'),
    url(r'^(?P<plan_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<plan_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<plan_id>[0-9]+)/delete/$', views.delete, name='delete'),
]

timeweb/tasks/urls.py
from django.conf.urls import url

from tasks import views


app_name = 'tasks'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.create, name='create'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<task_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<task_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<task_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<task_id>[0-9]+)/share/$', views.share, name='share'),
    url(r'^(?P<task_id>[0-9]+)/complete/$', views.complete, name='complete'),
    url(
        r'^(?P<task_id>[0-9]+)/uncomplete/$',
        views.uncomplete,
        name='uncomplete',
    ),
    url(r'^(?P<task_id>[0-9]+)/archive/$', views.archive, name='archive'),
    url(
        r'^(?P<task_id>[0-9]+)/unarchive/$',
        views.unarchive,
        name='unarchive',
    ),
    url(
        r'^(?P<task_id>[0-9]+)/block/(?P<blocking_task_id>[0-9]+)/$',
        views.block,
        name='block',
    ),
    url(
        r'^(?P<task_id>[0-9]+)/archive/(?P<target_task_id>[0-9]+)/$',
        views.target,
        name='target',
    ),
]

timeweb/timeweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^planned-tasks/', include('planned_tasks.urls')),
    url(r'^plans/', include('plans.urls')),
    url(r'^admin/', admin.site.urls),
]

timeweb/core/forms.py
import re

from dateutil.relativedelta import relativedelta
from django.forms import (
    TextInput,
    CharField,
    ValidationError,
)

from core.utils import serialize_relativedelta


class ListWidget(TextInput):
    def format_value(self, value):
        if isinstance(value, str):
            return value
        return ' '.join(value or [])


class ListField(CharField):
    widget = ListWidget

    def to_python(self, value):
        return [str(element) for element in (value or '').split()]


class RelativedeltaWidget(TextInput):
    def format_value(self, value):
        if isinstance(value, str):
            return value
        if value is None:
            return ''

        return serialize_relativedelta(value)


class RelativedeltaField(CharField):
    widget = RelativedeltaWidget

    def to_python(self, value):
        if value in self.empty_values:
            return None

        if re.match(
            (
                r'([+-]?\d+) (years|months|weeks|days|hours|minutes|seconds)'
                r'(,\s*([+-]?\d+)'
                r' (years|months|weeks|days|hours|minutes|seconds))*'
            ),
            value,
        ):
            try:
                return relativedelta(**{
                    key: int(value)
                    for value, key
                    in re.findall(
                        (
                            r'([+-]?\d+)'
                            r' (years|months|weeks|days|hours|minutes|seconds)'
                        ),
                        value,
                    )
                })
            except Exception:
                pass

        raise ValidationError('Invalid delta format', code='invalid')

timeweb/core/views.py
from datetime import datetime

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.conf import settings
from dateutil.relativedelta import relativedelta

from timelib import (
    create_session,
    Manager,
)
from core.utils import date_only


def index(request):
    if request.user.is_authenticated():
        manager = Manager(
            create_session(
                f'sqlite:///{settings.DATABASES["default"]["NAME"]}',
            ),
            request.user.username,
        )

        context = {
            'today_tasks': manager.get_tasks(
                from_time=date_only(datetime.today()),
                to_time=date_only(datetime.today() + relativedelta(days=1)),
                archived=False,
            ),
            'week_tasks': manager.get_tasks(
                from_time=date_only(datetime.today()),
                to_time=date_only(datetime.today() + relativedelta(days=7)),
                archived=False,
            ),
            'plans': manager.get_plans(),
        }
    else:
        context = {}

    return render(
        request,
        'core/index.html',
        context,
    )


def signup(request):
    if request.user.is_authenticated():
        return redirect('core:index')

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('core:index')
    else:
        form = UserCreationForm()

    return render(request, 'core/signup.html', {'form': form})

timeweb/core/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">ti.me</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% block tabs %}{% endblock %}
            </div>
        </nav>
        {% block content %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

timeweb/core/templates/tabs_snippet.html
{% if request.user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
        <li class="nav-item{% if active_tab == 'home' %} active{% endif %}">
            <a class="nav-link" href="{% url 'core:index' %}">Home{% if active_tab == 'home' %} <span class="sr-only">(current)</span>{% endif %}</a>
        </li>
        <li class="nav-item{% if active_tab == 'tasks' %} active{% endif %}">
            <a class="nav-link" href="{% url 'tasks:index' %}">Tasks{% if active_tab == 'tasks' %} <span class="sr-only">(current)</span>{% endif %}</a>
        </li>
        <li class="nav-item{% if active_tab == 'plans' %} active{% endif %}">
            <a class="nav-link" href="{% url 'plans:index' %}">Plans{% if active_tab == 'plans' %} <span class="sr-only">(current)</span>{% endif %}</a>
        </li>
    </ul>
    <span class="mr-3 navbar-text">{{ request.user.username }}</span>
    <a class="mr-3" href="{% url 'plans:check' %}?next={{ request.path }}"><span class="oi oi-reload"></span></a>
    <a href="{% url 'core:logout' %}"><span class="oi oi-account-logout"></span></a>
{% else %}
    <div class="mr-auto"></div>
    <a href="{% url 'core:login' %}"><span class="oi oi-account-login"></span></a>
{% endif %}