timeweb/core/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url

from core import views


app_name = 'core'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(
        r'^login/',
        auth_views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='core/login.html',
        ),
        name='login',
    ),
    url(r'^logout/', auth_views.logout_then_login, name='logout'),
    url(r'^signup/', views.signup, name='signup'),
]

timeweb/planned_tasks/urls.py
from django.conf.urls import url

from planned_tasks import views


app_name = 'planned_tasks'
urlpatterns = [
    url(r'^add/$', views.create, name='create'),
    url(r'^(?P<planned_task_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<planned_task_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<planned_task_id>[0-9]+)/delete/$', views.delete, name='delete'),
]

timeweb/plans/urls.py
from django.conf.urls import url

from plans import views


app_name = 'plans'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.create, name='create'),
    url(r'^check/$', views.check, name='check'),
    url(r'^(?P<plan_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<plan_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<plan_id>[0-9]+)/delete/$', views.delete, name='delete'),
]

timeweb/timeweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^planned-tasks/', include('planned_tasks.urls')),
    url(r'^plans/', include('plans.urls')),
    url(r'^admin/', admin.site.urls),
]

timeweb/plans/forms.py
from django.forms import (
    Form,
    IntegerField,
    DateTimeField,
    DateTimeInput,
)

from core.forms import RelativedeltaField


class CreateForm(Form):
    delta = RelativedeltaField(label='Delta')
    from_time = DateTimeField(
        widget=DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        label='From',
    )
    to_time = DateTimeField(
        widget=DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        label='To',
        required=False,
    )
    count = IntegerField(
        label='Count',
        required=False,
    )


class EditForm(Form):
    delta = RelativedeltaField(label='Delta')
    from_time = DateTimeField(
        widget=DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        label='From',
        required=False,
    )
    to_time = DateTimeField(
        widget=DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        label='To',
        required=False,
    )
    count = IntegerField(label='Count', required=False)

timeweb/plans/views.py
from datetime import (
    datetime,
    time,
)

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse

from plans.forms import (
    CreateForm,
    EditForm,
)
from core.utils import managed


@login_required
@managed
def index(request, manager):
    plans = manager.get_plans()

    return render(request, 'plans/index.html', {'plans': plans})


@login_required
@managed
def detail(request, plan_id, manager):
    plan = manager.get_plan(id=int(plan_id))

    return render(request, 'plans/detail.html', {'plan': plan})


@login_required
@managed
def create(request, manager):
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            with manager.save_after():
                plan = manager.create_plan(
                    delta=form.cleaned_data['delta'],
                    from_time=form.cleaned_data['from_time'],
                    to_time=form.cleaned_data['to_time'],
                    count=form.cleaned_data['count'],
                )
            return redirect('plans:detail', plan.id)
    else:
        form = CreateForm()
    return render(request, 'plans/create.html', {'form': form})


@login_required
@managed
def edit(request, plan_id, manager):
    plan = manager.get_plan(id=int(plan_id))

    if request.method == 'POST':
        form = EditForm(request.POST)
        if form.is_valid():
            with manager.save_after():
                plan.delta = form.cleaned_data['delta']
                plan.from_time = form.cleaned_data.get(
                    'from_time',
                    plan.from_time,
                )
                plan.to_time = form.cleaned_data.get(
                    'to_time',
                    None,
                )
                plan.count = form.cleaned_data['count']
            return redirect(
                request.POST.get(
                    'next',
                    reverse('plans:detail', args=[plan_id]),
                ),
            )
    else:
        form = EditForm(initial=vars(plan))

    return render(
        request,
        'plans/edit.html',
        {
            'form': form,
            'plan': plan,
            'next': request.GET.get(
                'next',
                reverse('plans:detail', args=[plan_id]),
            ),
        },
    )


@login_required
@managed
def delete(request, plan_id, manager):
    with manager.save_after():
        manager.delete_plan(id=int(plan_id))

    return redirect(
        request.GET.get('next', request.POST.get('next', 'plans:index')),
    )


@login_required
@managed
def check(request, manager):
    with manager.save_after():
        for update in manager.get_updates():
            with manager.save_after():
                manager.create_tasks_from_update(update)

    return redirect(
        request.GET.get('next', request.POST.get('next', 'plans:index')),
    )

timeweb/plans/templates/plans/base.html
{% extends 'base.html' %}

{% block tabs %}{% include 'tabs_snippet.html' with active_tab='plans' %}{% endblock %}

timeweb/plans/templates/plans/compact_snippet.html
{% load core_extras %}

<a class="badge badge-pill badge-primary" href="{% url 'plans:detail' plan.id %}">
    #{{ plan.id }}
    <small class="oi oi-clock"></small> {{ plan.delta|relativedelta|truncatechars:20 }}
    <small class="oi oi-reload"></small> {{ plan.last_count }}{% if plan.count is not None %} / {{ plan.count }}{% endif %}
    {% if plan.planned_tasks %}<small class="oi oi-layers"></small> {{ plan.planned_tasks|length }}{% endif %}
</a>

timeweb/plans/templates/plans/create.html
{% extends 'plans/base.html' %}

{% load widget_tweaks %}

{% block content %}
    <div class="container py-3">
        <form action="{% url 'plans:create' %}" method="POST">
            {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            {% csrf_token %}
            <div class="form-group">
                {{ form.delta.label_tag }}
                {% if form.delta.errors %}
                    {{ form.delta|add_class:'form-control is-invalid'|attr:'placeholder:1 weeks 11 hours 3 days' }}
                    <div class="invalid-feedback">{{ form.delta.errors }}</div>
                {% else %}
                    {{ form.delta|add_class:'form-control'|attr:'placeholder:1 weeks 11 hours 3 days' }}
                {% endif %}
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ form.from_time.label_tag }}
                        {% if form.from_time.errors %}
                            {{ form.from_time|add_class:'form-control mb-2 is-invalid' }}
                            <div class="invalid-feedback">{{ form.from_time.errors }}</div>
                        {% else %}
                            {{ form.from_time|add_class:'form-control mb-2' }}
                        {% endif %}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {{ form.to_time.label_tag }}
                        {% if form.to_time.errors %}
                            {{ form.to_time|add_class:'form-control mb-2 is-invalid' }}
                            <div class="invalid-feedback">{{ form.to_time.errors }}</div>
                        {% else %}
                            {{ form.to_time|add_class:'form-control mb-2' }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.count.label_tag }}
                {% if form.count.errors %}
                    {{ form.count|add_class:'form-control is-invalid' }}
                    <div class="invalid-feedback">{{ form.count.errors }}</div>
                {% else %}
                    {{ form.count|add_class:'form-control' }}
                {% endif %}
            </div>
            <input type="hidden" name="next" value="{{ next }}">
            <input class="btn btn-primary" type="submit" value="Create">
        </form>
    </div>
{% endblock %}

timeweb/plans/templates/plans/detail.html
{% extends 'plans/base.html' %}

{% load core_extras %}

{% block content %}
    <div class="container py-3">
        {% if 'error' in request.GET %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ request.GET.error }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">
                    #{{ plan.id }}
                </h4>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Delta:</div>
                        <div class="col">
                            {{ plan.delta|relativedelta }}
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Time:</div>
                        <div class="col">
                            {{ plan.from_time }}{% if plan.to_time %} - {{ plan.to_time }}{% endif %}
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Last time:</div>
                        <div class="col">
                            {{ plan.last_time }}
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col col-2">Last count:</div>
                        <div class="col">
                            {{ plan.last_count }}{% if plan.count is not None %} / {{ plan.count }}{% endif %}
                        </div>
                    </div>
                </li>
                {% if plan.planned_tasks %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col col-2">Planned tasks:</div>
                            <div class="col">
                                <ul class="list-inline">
                                    {% for planned_task in plan.planned_tasks %}
                                        <li class="list-inline-item">{% include 'planned_tasks/compact_snippet.html' with plan=planned_task %}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </li>
                {% endif %}
            </ul>
            <div class="card-body">
                <a class="btn btn-primary" href="{% url 'planned_tasks:create' %}?plan_id={{ plan.id }}&next={{ request.path }}">Plan task</a>
                <a class="btn btn-danger" href="{% url 'plans:delete' plan.id %}">Delete</a>
                <a href="{% url 'plans:edit' plan.id %}?next={{ request.path }}" class="btn btn-link">Edit</a>
            </div>
        </div>
    </div>
{% endblock %}

timeweb/plans/templates/plans/edit.html
{% extends 'plans/base.html' %}

{% load widget_tweaks %}

{% block content %}
    <div class="container py-3">
        <form action="{% url 'plans:edit' plan.id %}" method="POST">
            {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            {% csrf_token %}
            <div class="form-group">
                {{ form.delta.label_tag }}
                {% if form.delta.errors %}
                    {{ form.delta|add_class:'form-control is-invalid'|attr:'placeholder:1 weeks 11 hours 3 days' }}
                    <div class="invalid-feedback">{{ form.delta.errors }}</div>
                {% else %}
                    {{ form.delta|add_class:'form-control'|attr:'placeholder:1 weeks 11 hours 3 days' }}
                {% endif %}
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ form.from_time.label_tag }}
                        {% if form.from_time.errors %}
                            {{ form.from_time|add_class:'form-control mb-2 is-invalid' }}
                            <div class="invalid-feedback">{{ form.from_time.errors }}</div>
                        {% else %}
                            {{ form.from_time|add_class:'form-control mb-2' }}
                        {% endif %}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {{ form.to_time.label_tag }}
                        {% if form.to_time.errors %}
                            {{ form.to_time|add_class:'form-control mb-2 is-invalid' }}
                            <div class="invalid-feedback">{{ form.to_time.errors }}</div>
                        {% else %}
                            {{ form.to_time|add_class:'form-control mb-2' }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.count.label_tag }}
                {% if form.count.errors %}
                    {{ form.count|add_class:'form-control is-invalid'|attr:'placeholder:10' }}
                    <div class="invalid-feedback">{{ form.count.errors }}</div>
                {% else %}
                    {{ form.count|add_class:'form-control'|attr:'placeholder:10' }}
                {% endif %}
            </div>
            <input type="hidden" name="next" value="{{ next }}">
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

timeweb/plans/templates/plans/index.html
{% extends 'plans/base.html' %}

{% block content %}
    <div class="container py-3">
        {% if 'error' in request.GET %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ request.GET.error }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <h3>Plans</h3>
        {% include 'plans/list_snippet.html' with plans=plans %}
        <a class="btn btn-primary" href="{% url 'plans:create' %}">Add plan</a>
    </div>
{% endblock %}

timeweb/plans/templates/plans/list_snippet.html
{% load core_extras %}

<table class="table">
    {% if plans %}
        <tbody>
            {% for plan in plans %}
                <tr>
                    <th scope="row">
                        <a href="{% url 'plans:detail' plan.id %}">#{{ plan.id }}</a>
                    </th>
                    <td><a href="{% url 'plans:detail' plan.id %}">{{ plan.delta|relativedelta }}</a></td>
                    <td>
                        {{ plan.from_time }}{% if plan.to_time %} - {{ plan.to_time }}{% endif %}
                    </td>
                    <td>
                        {% if plan.last_count %}
                            Last check at {{ plan.last_time }}
                        {% else %}
                            Never checked
                        {% endif %}
                    </td>
                    <td>Checked {{ plan.last_count }}{% if plan.count is not None %} / {{ plan.count }}{% endif %} times</td>
                    <td>
                        <ul class="list-inline">
                            {% for planned_task in plan.planned_tasks %}
                                <li class="list-inline-item">{% include 'planned_tasks/compact_snippet.html' with planned_task=planned_task %}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-link" type="button" id="plan-menu-{{ plan.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="oi oi-menu"></span></button>
                            <div class="dropdown-menu" aria-labelledby="plan-menu-{{ plan.id }}">
                                <a class="dropdown-item" href="{% url 'planned_tasks:create' %}?plan_id={{ plan.id }}&next={{ request.path }}"><span class="oi oi-plus"></span> Plan task</a>
                                <a class="dropdown-item" href="{% url 'plans:edit' plan.id %}?next={{ request.path }}"><span class="oi oi-pencil"></span> Edit</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'plans:delete' plan.id %}?next={{ request.path }}"><span class="oi oi-trash"></span> Delete</a>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    {% else %}
        <div class="alert alert-primary">No plans in this list</div>
    {% endif %}
</table>